/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus')['ElAlert']
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElDescriptions: typeof import('element-plus')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus')['ElDialog']
    ElEmpty: typeof import('element-plus')['ElEmpty']
    ElForm: typeof import('element-plus')['ElForm']
    ElFormItem: typeof import('element-plus')['ElFormItem']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElImage: typeof import('element-plus')['ElImage']
    ElInput: typeof import('element-plus')['ElInput']
    ElProgress: typeof import('element-plus')['ElProgress']
    ElRadioButton: typeof import('element-plus')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus')['ElRadioGroup']
    ElResult: typeof import('element-plus')['ElResult']
    ElSkeleton: typeof import('element-plus')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus')['ElSkeletonItem']
    ElSlider: typeof import('element-plus')['ElSlider']
    ElTag: typeof import('element-plus')['ElTag']
    ElUpload: typeof import('element-plus')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepNavigation: typeof import('./src/components/StepNavigation.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus')['ElLoadingDirective']
  }
}
